[package]
name = "ultrafinance-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
ultrafinance-core = { path = "../ultrafinance-core", features = ["openapi"] }
utoipa.workspace = true
utoipa-axum = "0.3"
utoipa-scalar = { version = "0.4", features = ["axum"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
