// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateTrigger { function_id: number, params: Record<string, string>, event: string, name: string, }