// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ExchangeRate { base_code: string, conversion_rates: Record<string, number>, last_update: string, }