// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Function { id: number, name: string, type: string, source: string, created_at: string, updated_at: string, params: Record<string, { name: string, type: string, }> | null, }