// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Location { address: string | null, city: string | null, state: string | null, postcode: string | null, country: string | null, latitude: number | null, longitude: number | null, google_maps_url: string | null, apple_maps_url: string | null, store_number: number | null, }