// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";

export interface Merchant { id: number, name: string, logo_url: string | null, location: string | null, location_structured: Location | null, labels: string | null, external_id: string | null, website: string | null, created_at: string, }