// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Requisition { id: string, status: string, redirect: string, accounts: Array<string>, link: string, }