// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StdioMsg } from "./StdioMsg";

export interface TestFunctionResult { result: string, console: Array<StdioMsg>, }