// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TriggerLog { id: number, payload: string, status: string, user_id: number, trigger_id: number, created_at: string, updated_at: string, }