// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerFilter } from "./TriggerFilter";
import type { TriggerParams } from "./TriggerParams";

export interface Trigger { id: number, event: string, name: string, filter: TriggerFilter, params: TriggerParams, function_id: number, created_at: string, updated_at: string, }