// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateUser { id: number | null, name: string | null, email: string | null, password: string | null, primary_currency: string | null, }