// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerFilter } from "./TriggerFilter";

export interface UpdateTrigger { id: number | null, name: string | null, params: string | null, event: string | null, filter: TriggerFilter | null, function_id: number | null, }