[package]
name = "ultrafinance-core"
version.workspace = true
edition.workspace = true

[features]
openapi = ["dep:utoipa"]

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
unicode-normalization.workspace = true
rapidfuzz.workspace = true
regex.workspace = true
uuid.workspace = true
tokio.workspace = true
csv.workspace = true
utoipa = { workspace = true, optional = true }

postgres.workspace = true
postgres-native-tls.workspace = true
native-tls.workspace = true

[dev-dependencies]
strsim.workspace = true
